management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9092
spring:
  application:
    name: GREETAPI
  boot:
    admin:
      client:
        url: http://localhost:9090
